### ISSUE TITLE
Specific version for ignite ?

### ISSUE THREAD

**Issue by sdesrozis** [vfdev-5/py_config_runner#7]
Does it make sense to have a specific launcher for ignite (main train script + config) using `idist` ?

**Comment by vfdev-5** [comment]
@sdesrozis sorry, I do not get the idea about introducing ignite there. Please, provide some details :)

**Comment by sdesrozis** [comment]
`idist` from `ignite` allows to address multiple models (xla, torch.dist, slurm) / hardware (tpu, cpu, gpu). The idea is to have a parallel launcher using `idist` spawn feature.

Obviously, the downside is to restrict the launcher to PyTorch apps.

**Comment by vfdev-5** [comment]
Sorry, still do not get the details. Could you, please, provide a concrete proposed API usage ?

**Comment by sdesrozis** [comment]
Consider `training.py` and `config.py` from `README.md`. These codes should be modified to use `DistributedDataParallel`, distributed `DataLoader` with sampler, scaled `lr` or `batch_size`. The model could be `dist` (but `idist` should be ok?).

Single node 
``` 
py_config_runner training.py config.py —nproc_per_node=2
```

Multiple node
``` 
py_config_runner training.py config.py —nproc_per_node=4 —nnodes=4 —master_addr=<adds> —rank=<rank>
```

**Comment by vfdev-5** [comment]
OK, I see more or less the request. Let's say a half of that can already be done with `torch dist launch`:
```python
python -m torch.distributed.launch --nproc_per_node=num_gpus -m py_config_runner training.py config.py --manual_config_load
```
Another half is about using spawn, so, does this request is about passing additional arguments to required `run` function ?

**Comment by sdesrozis** [comment]
Idea is to don’t have to define `dist.initialize()` and `dist.finalize()` (or `spawn` alternatives). Maybe it’s more complicated and blocking than helping.

And yes, improve the launcher to be compatible with `argparse` should be great (and easy to do I think).

**Comment by vfdev-5** [comment]
I think this issue can be closed now as ignite already has `idist` etc.
